# Generated by Django 6.0.4 on 2026-04-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('need_type', models.CharField(choices=[('food', 'Food'), ('medical', 'Medical'), ('water', 'Water'), ('shelter', 'Shelter'), ('electricity', 'Electricity'), ('general', 'General')], max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('location_text', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
