# Generated by Django 6.0.4 on 2026-06-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='pincode',
        ),
    ]
