# Generated by Django 6.0.4 on 2026-06-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NGOData',
        ),
    ]
