# Generated by Django 6.0.4 on 2026-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
