# Generated by Django 6.0.4 on 2026-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
