# Generated by Django 6.0.4 on 2026-06-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_assignment_created_at_assignment_updated_at_and_more'),
        ('volunteers', '0005_remove_volunteer_points_volunteer_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_needs',
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='people_count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskUpdate',
        ),
    ]
