# Generated by Django 6.0.7 on 2026-08-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_need_row_hash'),
        ('tasks', '0010_task_description_task_instructions_task_source_needs_and_more'),
        ('users', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['ngo', 'status'], name='tasks_task_ngo_id_60b299_idx'),
        ),
    ]
