# Generated by Django 6.0.4 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='row_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
