# Generated by Django 6.0.4 on 2026-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
