# Generated by Django 6.0.4 on 2026-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteer_points_volunteer_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
