# Generated by Django 6.0.4 on 2026-06-24 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_volunteer_latitude_volunteer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
