# Generated by Django 6.0.4 on 2026-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='points',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
