# Generated by Django 6.0.4 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_remove_volunteer_points_volunteer_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
